# Generated by Django 2.2.28 on 2026-03-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybase.Page'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybase.PostHistory'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='topic_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybase.TopicHistory'),
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
